In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [5]:
ab = pd.read_csv("C:/Users/Gokula Praveen/Downloads/Shopping_Customer_Dataset")

In [6]:
ab.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [7]:
ab.tail()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [8]:
ab.size

7000

In [9]:
ab.shape

(1000, 7)

In [10]:
ab.columns

Index(['Gender', 'Product_Category', 'Payment_Method', 'Membership_Level',
       'City', 'Customer_Rating', 'Total_Items'],
      dtype='str')

In [11]:
ab.isnull()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False

In [12]:
ab.isnull().sum()

Gender              27
Product_Category     0
Payment_Method       0
Membership_Level     0
City                 0
Customer_Rating     28
Total_Items          0
dtype: int64

In [13]:
ab.dropna(inplace=True)

In [14]:
ab.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 945, dtype: bool

In [15]:
ab.duplicated().sum()

np.int64(1)

In [16]:
ab.drop_duplicates()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
...,...,...,...,...,...,...,...
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [17]:
ab.dropna(inplace = True)

In [18]:
df=pd.read_csv("C:/Users/Gokula Praveen/Downloads/load_forecasting_dataset_corrected.csv")

In [19]:
df.head()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW)
0,1/1/2020 0:00,28.993428,75.011269,1.053861,4.140513,185.892561,925.621430,502.915605,20.454440,2,0,1,Summer,0,1599.342831
1,1/1/2020 0:15,27.723471,77.024015,1.085152,9.446997,281.782650,1020.823521,497.286366,27.776449,2,0,1,Summer,0,1472.347140
2,1/1/2020 0:30,29.295377,74.732958,3.363800,4.265813,328.942058,1028.847455,488.816292,21.097420,2,0,1,Summer,0,1629.537708
3,1/1/2020 0:45,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2,0,1,Summer,1,1804.605971
4,1/1/2020 1:00,27.531693,79.709858,1.366819,4.201393,205.494256,934.477462,488.565716,27.079114,2,1,1,Summer,0,1453.169325

In [20]:
df["Time"]=pd.to_datetime(df["Timestamp"])

In [21]:
df.tail()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW),Time
189883,5/31/2025 22:45,27.433177,82.943227,1.564385,0.476854,214.276578,986.122824,487.823955,17.183842,5,22,5,Fall,0,1443.317681,2025-05-31 22:45:00
189884,5/31/2025 23:00,32.085127,84.159944,1.389473,0.309841,308.798749,970.258350,515.405431,29.773656,5,23,5,Fall,0,1908.512650,2025-05-31 23:00:00
189885,5/31/2025 23:15,27.620201,87.091108,2.722335,1.422315,282.487744,1007.429961,509.295868,24.883951,5,23,5,Fall,0,1462.020111,2025-05-31 23:15:00
189886,5/31/2025 23:30,29.378415,75.743129,2.317605,9.383305,246.291089,1019.239724,536.514530,27.765615,5,23,5,Fall,0,1637.841485,2025-05-31 23:30:00
189887,5/31/2025 23:45,27.737078,83.529497,0.914573,9.901955,299.088224,1020.425273,518.742211,15.496762,5,23,5,Fall,0,1473.707828,2025-05-31 23:45:00

In [22]:
ab.loc[0]

Gender                 Male
Product_Category     Beauty
Payment_Method         Cash
Membership_Level    Premium
City                Chicago
Customer_Rating         4.6
Total_Items               8
Name: 0, dtype: object

In [23]:
ab.loc[0:5]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
5,Male,Electronics,Debit Card,Silver,Chicago,2.2,6

In [24]:
ab.iloc[0]

Gender                 Male
Product_Category     Beauty
Payment_Method         Cash
Membership_Level    Premium
City                Chicago
Customer_Rating         4.6
Total_Items               8
Name: 0, dtype: object

In [33]:
ab.iloc[930:-1]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
984,Female,Electronics,Cash,Gold,Houston,1.4,7
985,Female,Electronics,Cash,Bronze,Miami,4.1,10
986,Female,Electronics,Credit Card,Gold,Houston,4.9,6
987,Male,Electronics,Credit Card,Gold,Houston,4.9,6
988,Male,Electronics,Debit Card,Gold,Miami,4.5,6
989,Female,Clothing,Cash,Silver,Miami,3.4,6
990,Female,Beauty,PayPal,Gold,Los Angeles,3.8,10
991,Female,Sports,PayPal,Silver,Miami,2.1,7
993,Female,Clothing,Credit Card,Bronze,Los Angeles,2.8,6
994,Male,Clothing,PayPal,Bronze,Los Angeles,2.9,3
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2

In [39]:
ab.iloc[3:5,1:6]

,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating
3,Electronics,Cash,Silver,New York,3.7
4,Sports,PayPal,Silver,Los Angeles,4.8

In [41]:
ab[ab["Total_Items"]>5]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
5,Male,Electronics,Debit Card,Silver,Chicago,2.2,6
8,Female,Beauty,Credit Card,Silver,New York,1.9,10
...,...,...,...,...,...,...,...
993,Female,Clothing,Credit Card,Bronze,Los Angeles,2.8,6
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [42]:
ab[ab["Total_Items"]<=5]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
3,Female,Electronics,Cash,Silver,New York,3.7,5
6,Male,Clothing,Credit Card,Silver,Los Angeles,1.0,3
7,Female,Electronics,Cash,Silver,Houston,2.1,3
12,Female,Sports,Credit Card,Bronze,New York,1.1,2
...,...,...,...,...,...,...,...
975,Male,Electronics,PayPal,Gold,New York,2.7,2
979,Female,Clothing,PayPal,Gold,Chicago,3.3,2
983,Male,Electronics,PayPal,Silver,Miami,2.5,1
994,Male,Clothing,PayPal,Bronze,Los Angeles,2.9,3
998,Female,Beauty,PayPal,Gold,Houston,4.7,2

In [43]:
ab[(ab["Customer_Rating"]>=2.5)&(ab["Total_Items"]<5)]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
13,Male,Clothing,Cash,Gold,New York,3.9,2
16,Male,Clothing,Debit Card,Silver,Los Angeles,3.2,2
36,Male,Clothing,Debit Card,Gold,Chicago,3.3,3
40,Male,Clothing,Debit Card,Bronze,Houston,2.5,1
...,...,...,...,...,...,...,...
975,Male,Electronics,PayPal,Gold,New York,2.7,2
979,Female,Clothing,PayPal,Gold,Chicago,3.3,2
983,Male,Electronics,PayPal,Silver,Miami,2.5,1
994,Male,Clothing,PayPal,Bronze,Los Angeles,2.9,3
998,Female,Beauty,PayPal,Gold,Houston,4.7,2

In [44]:
ab[(ab["Customer_Rating"]>=2.5)|(ab["Total_Items"]<5)]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
...,...,...,...,...,...,...,...
990,Female,Beauty,PayPal,Gold,Los Angeles,3.8,10
993,Female,Clothing,Credit Card,Bronze,Los Angeles,2.8,6
994,Male,Clothing,PayPal,Bronze,Los Angeles,2.9,3
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
998,Female,Beauty,PayPal,Gold,Houston,4.7,2

In [47]:
ab[(ab["Customer_Rating"]<=2.5)!="Male"]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
...,...,...,...,...,...,...,...
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [49]:
ab.sort_values("Total_Items")

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
495,Male,Beauty,Debit Card,Silver,Houston,2.2,1
961,Female,Home & Kitchen,Debit Card,Gold,Los Angeles,1.8,1
504,Female,Beauty,Credit Card,Silver,Chicago,3.0,1
507,Female,Home & Kitchen,PayPal,Premium,New York,1.5,1
509,Female,Sports,Debit Card,Bronze,Los Angeles,4.2,1
...,...,...,...,...,...,...,...
580,Male,Sports,Cash,Gold,Los Angeles,3.4,10
417,Male,Home & Kitchen,Debit Card,Bronze,Los Angeles,1.7,10
409,Male,Sports,Credit Card,Gold,Chicago,2.0,10
977,Male,Beauty,Credit Card,Gold,Houston,2.8,10
968,Female,Clothing,Cash,Silver,New York,1.2,10

In [50]:
ab.sort_values("Total_Items",ascending=False)

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
8,Female,Beauty,Credit Card,Silver,New York,1.9,10
982,Male,Sports,Debit Card,Silver,Los Angeles,1.4,10
10,Male,Clothing,Cash,Silver,Houston,3.5,10
474,Female,Beauty,Debit Card,Bronze,New York,1.9,10
...,...,...,...,...,...,...,...
57,Male,Sports,Debit Card,Premium,Houston,2.6,1
970,Female,Clothing,Cash,Premium,New York,1.5,1
969,Male,Beauty,Debit Card,Silver,Los Angeles,4.3,1
967,Male,Sports,Credit Card,Premium,Los Angeles,1.1,1
973,Male,Clothing,Debit Card,Silver,Houston,4.4,1

In [51]:
ab["Totat_rating"]=ab["Customer_Rating"]*ab["Total_Items"]

In [52]:
ab.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Totat_rating
0,Male,Beauty,Cash,Premium,Chicago,4.6,8,36.8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2,8.4
2,Female,Sports,Debit Card,Silver,Miami,3.7,9,33.3
3,Female,Electronics,Cash,Silver,New York,3.7,5,18.5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10,48.0

In [55]:
ab.groupby("Customer_Rating")["Total_Items"].agg(['min', 'max', 'sum', 'mean', 'count', 'std'])

                 min  max  sum      mean  count       std
Customer_Rating
1.0                1    9   60  5.000000     12  2.662876
1.1                1   10   66  4.125000     16  3.201562
1.2                1   10  181  5.484848     33  2.563216
1.3                1   10  104  4.952381     21  2.654735
1.4                1   10  141  6.409091     22  2.702011
1.5                1   10  142  4.896552     29  3.062968
1.6                1   10  117  5.571429     21  2.675284
1.7                1   10  185  5.967742     31  2.834124
1.8                1   10  134  4.785714     28  2.753545
1.9                1   10  111  6.166667     18  3.240370
2.0                1   10  122  4.880000     25  2.891366
2.1                1    7   63  3.937500     16  2.015564
2.2                1   10  105  5.000000     21  2.774887
2.3                1   10  169  6.500000     26  2.716616
2.4                1   10  189  6.096774     31  3.389738
2.5                1   10  107  4.280000     25  3.372931
2.6                1   10  152  5.629630     27  2.618692
2.7                2   10  149  5.730769     26  2.646623
2.8                1   10  102  5.666667     18  2.910428
2.9                1   10  115  6.052632     19  3.407079
3.0                1   10  142  5.916667     24  2.569329
3.1                1   10  103  6.058824     17  3.362859
3.2                1   10  183  5.718750     32  2.385905
3.3                1   10  170  5.666667     30  2.880773
3.4                1   10  169  5.827586     29  2.765463
3.5                2   10  117  6.500000     18  3.053445
3.6                1   10  101  5.050000     20  3.170173
3.7                1   10  174  6.000000     29  2.507133
3.8                2   10  108  5.684211     19  3.074133
3.9                1   10  128  5.818182     22  3.567530
4.0                1   10  134  5.153846     26  3.042266
4.1                1   10  113  5.380952     21  3.106062
4.2                1   10  109  4.739130     23  3.346876
4.3                1   10  122  5.083333     24  3.215677
4.4                1   10  153  6.120000     25  2.758623
4.5                1   10  123  5.347826     23  2.690196
4.6                2   10  120  6.315789     19  2.829461
4.7                1   10  102  4.857143     21  2.780031
4.8                1   10  172  5.733333     30  2.803118
4.9                1   10  106  5.888889     18  3.305768
5.0                1   10   55  5.500000     10  2.798809

In [56]:
ab.groupby("Customer_Rating")["Total_Items"].sum()

Customer_Rating
1.0     60
1.1     66
1.2    181
1.3    104
1.4    141
1.5    142
1.6    117
1.7    185
1.8    134
1.9    111
2.0    122
2.1     63
2.2    105
2.3    169
2.4    189
2.5    107
2.6    152
2.7    149
2.8    102
2.9    115
3.0    142
3.1    103
3.2    183
3.3    170
3.4    169
3.5    117
3.6    101
3.7    174
3.8    108
3.9    128
4.0    134
4.1    113
4.2    109
4.3    122
4.4    153
4.5    123
4.6    120
4.7    102
4.8    172
4.9    106
5.0     55
Name: Total_Items, dtype: int64

In [57]:
ab.groupby("Customer_Rating")["Total_Items"].min()

Customer_Rating
1.0    1
1.1    1
1.2    1
1.3    1
1.4    1
1.5    1
1.6    1
1.7    1
1.8    1
1.9    1
2.0    1
2.1    1
2.2    1
2.3    1
2.4    1
2.5    1
2.6    1
2.7    2
2.8    1
2.9    1
3.0    1
3.1    1
3.2    1
3.3    1
3.4    1
3.5    2
3.6    1
3.7    1
3.8    2
3.9    1
4.0    1
4.1    1
4.2    1
4.3    1
4.4    1
4.5    1
4.6    2
4.7    1
4.8    1
4.9    1
5.0    1
Name: Total_Items, dtype: int64

In [58]:
ab.groupby("Customer_Rating")["Total_Items"].max()

Customer_Rating
1.0     9
1.1    10
1.2    10
1.3    10
1.4    10
1.5    10
1.6    10
1.7    10
1.8    10
1.9    10
2.0    10
2.1     7
2.2    10
2.3    10
2.4    10
2.5    10
2.6    10
2.7    10
2.8    10
2.9    10
3.0    10
3.1    10
3.2    10
3.3    10
3.4    10
3.5    10
3.6    10
3.7    10
3.8    10
3.9    10
4.0    10
4.1    10
4.2    10
4.3    10
4.4    10
4.5    10
4.6    10
4.7    10
4.8    10
4.9    10
5.0    10
Name: Total_Items, dtype: int64

In [59]:
ab.groupby("Customer_Rating")["Total_Items"].count()

Customer_Rating
1.0    12
1.1    16
1.2    33
1.3    21
1.4    22
1.5    29
1.6    21
1.7    31
1.8    28
1.9    18
2.0    25
2.1    16
2.2    21
2.3    26
2.4    31
2.5    25
2.6    27
2.7    26
2.8    18
2.9    19
3.0    24
3.1    17
3.2    32
3.3    30
3.4    29
3.5    18
3.6    20
3.7    29
3.8    19
3.9    22
4.0    26
4.1    21
4.2    23
4.3    24
4.4    25
4.5    23
4.6    19
4.7    21
4.8    30
4.9    18
5.0    10
Name: Total_Items, dtype: int64

In [60]:
ab.groupby("Customer_Rating")["Total_Items"].mean()

Customer_Rating
1.0    5.000000
1.1    4.125000
1.2    5.484848
1.3    4.952381
1.4    6.409091
1.5    4.896552
1.6    5.571429
1.7    5.967742
1.8    4.785714
1.9    6.166667
2.0    4.880000
2.1    3.937500
2.2    5.000000
2.3    6.500000
2.4    6.096774
2.5    4.280000
2.6    5.629630
2.7    5.730769
2.8    5.666667
2.9    6.052632
3.0    5.916667
3.1    6.058824
3.2    5.718750
3.3    5.666667
3.4    5.827586
3.5    6.500000
3.6    5.050000
3.7    6.000000
3.8    5.684211
3.9    5.818182
4.0    5.153846
4.1    5.380952
4.2    4.739130
4.3    5.083333
4.4    6.120000
4.5    5.347826
4.6    6.315789
4.7    4.857143
4.8    5.733333
4.9    5.888889
5.0    5.500000
Name: Total_Items, dtype: float64

In [61]:
ab.groupby("Customer_Rating")["Total_Items"].std()

Customer_Rating
1.0    2.662876
1.1    3.201562
1.2    2.563216
1.3    2.654735
1.4    2.702011
1.5    3.062968
1.6    2.675284
1.7    2.834124
1.8    2.753545
1.9    3.240370
2.0    2.891366
2.1    2.015564
2.2    2.774887
2.3    2.716616
2.4    3.389738
2.5    3.372931
2.6    2.618692
2.7    2.646623
2.8    2.910428
2.9    3.407079
3.0    2.569329
3.1    3.362859
3.2    2.385905
3.3    2.880773
3.4    2.765463
3.5    3.053445
3.6    3.170173
3.7    2.507133
3.8    3.074133
3.9    3.567530
4.0    3.042266
4.1    3.106062
4.2    3.346876
4.3    3.215677
4.4    2.758623
4.5    2.690196
4.6    2.829461
4.7    2.780031
4.8    2.803118
4.9    3.305768
5.0    2.798809
Name: Total_Items, dtype: float64

In [62]:
n = LabelEncoder()
ab["Gender2"]=n.fit_transform(ab["Gender"])

In [63]:
ab.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Totat_rating,Gender2
0,Male,Beauty,Cash,Premium,Chicago,4.6,8,36.8,1
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2,8.4,0
2,Female,Sports,Debit Card,Silver,Miami,3.7,9,33.3,0
3,Female,Electronics,Cash,Silver,New York,3.7,5,18.5,0
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10,48.0,1

In [67]:
o=OrdinalEncoder(categories=[["Premium","Gold","Silver","Bronze"]])
ab["Membership_Level2"]=o.fit_transform(ab[["Membership_Level"]])
ab.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Totat_rating,Gender2,Membership_Level2
0,Male,Beauty,Cash,Premium,Chicago,4.6,8,36.8,1,0.0
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2,8.4,0,3.0
2,Female,Sports,Debit Card,Silver,Miami,3.7,9,33.3,0,2.0
3,Female,Electronics,Cash,Silver,New York,3.7,5,18.5,0,2.0
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10,48.0,1,2.0

In [ ]:
ab=pd.get_dummies(ab["City"])