In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
ab = pd.read_csv("C:/Users/Gokula Praveen/Downloads/sales_data.csv")

In [5]:
ab.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [6]:
ab.tail()

    OrderID        Date     Product     Category  Quantity  UnitPrice
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [11]:
ab.loc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [12]:
ab.loc[0:20]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
16     1027  2026-01-06      Tablet  Electronics         2        450
17     1061  2026-01-07  Headphones  Accessories         3        150
18     1058  2026-01-07      Laptop  Electronics         2       1200
19     1077  2026-01-07  Headphones  Accessories         2        150
20     1001  2026-01-07  Smartphone  Electronics         4        800

In [14]:
ab.iloc[1:11,0:5]

    OrderID        Date     Product     Category  Quantity
1      1100  2026-01-02  Headphones  Accessories         2
2      1028  2026-01-02      Laptop  Electronics         2
3      1089  2026-01-02      Laptop  Electronics         3
4      1023  2026-01-02      Tablet  Electronics         4
5      1072  2026-01-02  Smartphone  Electronics         4
6      1055  2026-01-03  Headphones  Accessories         1
7      1020  2026-01-03      Laptop  Electronics         1
8      1082  2026-01-03  Smartphone  Electronics         4
9      1085  2026-01-04      Laptop  Electronics         1
10     1088  2026-01-04      Tablet  Electronics         4

In [15]:
ab[ab["UnitPrice"]>1000]

    OrderID        Date Product     Category  Quantity  UnitPrice
2      1028  2026-01-02  Laptop  Electronics         2       1200
3      1089  2026-01-02  Laptop  Electronics         3       1200
7      1020  2026-01-03  Laptop  Electronics         1       1200
9      1085  2026-01-04  Laptop  Electronics         1       1200
18     1058  2026-01-07  Laptop  Electronics         2       1200
23     1018  2026-01-08  Laptop  Electronics         2       1200
24     1087  2026-01-08  Laptop  Electronics         4       1200
36     1025  2026-01-12  Laptop  Electronics         3       1200
42     1048  2026-01-15  Laptop  Electronics         3       1200
43     1004  2026-01-15  Laptop  Electronics         2       1200
46     1044  2026-01-16  Laptop  Electronics         4       1200
47     1038  2026-01-17  Laptop  Electronics         2       1200
48     1084  2026-01-17  Laptop  Electronics         4       1200
50     1086  2026-01-18  Laptop  Electronics         1       1200
51     1097  2026-01-18  Laptop  Electronics         2       1200
66     1021  2026-01-22  Laptop  Electronics         1       1200
67     1095  2026-01-22  Laptop  Electronics         1       1200
68     1092  2026-01-22  Laptop  Electronics         1       1200
69     1052  2026-01-23  Laptop  Electronics         3       1200
71     1015  2026-01-24  Laptop  Electronics         4       1200
73     1019  2026-01-24  Laptop  Electronics         3       1200
78     1033  2026-01-26  Laptop  Electronics         4       1200
81     1010  2026-01-26  Laptop  Electronics         1       1200
87     1074  2026-01-28  Laptop  Electronics         3       1200
93     1035  2026-01-29  Laptop  Electronics         1       1200

In [20]:
ab[ab["UnitPrice"]>=800]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
5      1072  2026-01-02  Smartphone  Electronics         4        800
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
18     1058  2026-01-07      Laptop  Electronics         2       1200
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
23     1018  2026-01-08      Laptop  Electronics         2       1200
24     1087  2026-01-08      Laptop  Electronics         4       1200
35     1032  2026-01-12  Smartphone  Electronics         1        800
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
42     1048  2026-01-15      Laptop  Electronics         3       1200
43     1004  2026-01-15      Laptop  Electronics         2       1200
46     1044  2026-01-16      Laptop  Electronics         4       1200
47     1038  2026-01-17      Laptop  Electronics         2       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
50     1086  2026-01-18      Laptop  Electronics         1       1200
51     1097  2026-01-18      Laptop  Electronics         2       1200
55     1050  2026-01-19  Smartphone  Electronics         3        800
56     1053  2026-01-20  Smartphone  Electronics         2        800
62     1071  2026-01-21  Smartphone  Electronics         3        800
66     1021  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
75     1037  2026-01-25  Smartphone  Electronics         2        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
81     1010  2026-01-26      Laptop  Electronics         1       1200
87     1074  2026-01-28      Laptop  Electronics         3       1200
93     1035  2026-01-29      Laptop  Electronics         1       1200
94     1007  2026-01-29  Smartphone  Electronics         4        800

In [21]:
ab[ab["UnitPrice"]<1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[75 rows x 6 columns]

In [22]:
ab[ab["UnitPrice"]<=800]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[75 rows x 6 columns]

In [25]:
ab[(ab["UnitPrice"]>1000)&(ab["Quantity"]<2)]

    OrderID        Date Product     Category  Quantity  UnitPrice
7      1020  2026-01-03  Laptop  Electronics         1       1200
9      1085  2026-01-04  Laptop  Electronics         1       1200
50     1086  2026-01-18  Laptop  Electronics         1       1200
66     1021  2026-01-22  Laptop  Electronics         1       1200
67     1095  2026-01-22  Laptop  Electronics         1       1200
68     1092  2026-01-22  Laptop  Electronics         1       1200
81     1010  2026-01-26  Laptop  Electronics         1       1200
93     1035  2026-01-29  Laptop  Electronics         1       1200

In [27]:
ab[(ab["UnitPrice"]<500)|(ab["Quantity"]<2)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
1      1100  2026-01-02  Headphones  Accessories         2        150
4      1023  2026-01-02      Tablet  Electronics         4        450
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[71 rows x 6 columns]

In [29]:
ab[(ab["Quantity"]>2)!=500]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [31]:
ab.sort_values("OrderID")

    OrderID        Date     Product     Category  Quantity  UnitPrice
20     1001  2026-01-07  Smartphone  Electronics         4        800
57     1002  2026-01-20  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
43     1004  2026-01-15      Laptop  Electronics         2       1200
31     1005  2026-01-11  Smartwatch  Accessories         4        250
..      ...         ...         ...          ...       ...        ...
92     1096  2026-01-29  Smartwatch  Accessories         1        250
51     1097  2026-01-18      Laptop  Electronics         2       1200
80     1098  2026-01-26      Tablet  Electronics         3        450
37     1099  2026-01-12  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150

[100 rows x 6 columns]

In [32]:
ab.sort_values("OrderID",ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
1      1100  2026-01-02  Headphones  Accessories         2        150
37     1099  2026-01-12  Smartphone  Electronics         3        800
80     1098  2026-01-26      Tablet  Electronics         3        450
51     1097  2026-01-18      Laptop  Electronics         2       1200
92     1096  2026-01-29  Smartwatch  Accessories         1        250
..      ...         ...         ...          ...       ...        ...
31     1005  2026-01-11  Smartwatch  Accessories         4        250
43     1004  2026-01-15      Laptop  Electronics         2       1200
91     1003  2026-01-29  Headphones  Accessories         3        150
57     1002  2026-01-20  Headphones  Accessories         3        150
20     1001  2026-01-07  Smartphone  Electronics         4        800

[100 rows x 6 columns]

In [33]:
ab["Sales"] = ab["Quantity"]*ab["UnitPrice"]

In [34]:
ab.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
0     1031  2026-01-01  Smartphone  Electronics         3        800   2400
1     1100  2026-01-02  Headphones  Accessories         2        150    300
2     1028  2026-01-02      Laptop  Electronics         2       1200   2400
3     1089  2026-01-02      Laptop  Electronics         3       1200   3600
4     1023  2026-01-02      Tablet  Electronics         4        450   1800

In [35]:
ab["Total"] = ab["Quantity"]+ab["UnitPrice"]

In [36]:
ab.head()

,OrderID,Date,Product,Category,Quantity,UnitPrice,Sales,Total
0,1031,2026-01-01,Smartphone,Electronics,3,800,2400,803
1,1100,2026-01-02,Headphones,Accessories,2,150,300,152
2,1028,2026-01-02,Laptop,Electronics,2,1200,2400,1202
3,1089,2026-01-02,Laptop,Electronics,3,1200,3600,1203
4,1023,2026-01-02,Tablet,Electronics,4,450,1800,454

In [37]:
ab.groupby("Category")["Sales"].sum()

Category
Accessories     22750
Electronics    127600
Name: Sales, dtype: int64

In [40]:
ab.groupby("Category")["Total"].min()

Category
Accessories    151
Electronics    451
Name: Total, dtype: int64

In [41]:
ab.groupby("Category")["Sales"].max()

Category
Accessories    1000
Electronics    4800
Name: Sales, dtype: int64

In [42]:
ab.groupby("Category")["Total"].mean()

Category
Accessories    200.261905
Electronics    854.396552
Name: Total, dtype: float64

In [43]:
ab.groupby("Category")["Sales"].count()

Category
Accessories    42
Electronics    58
Name: Sales, dtype: int64

In [44]:
ab.groupby("Category")["Total"].std()

Category
Accessories     50.952421
Electronics    332.087229
Name: Total, dtype: float64

In [39]:
ab.groupby("Category")["Sales"].agg(['min', 'max', 'sum', 'mean', 'count', 'std'])

             min   max     sum         mean  count          std
Category
Accessories  150  1000   22750   541.666667     42   313.889189
Electronics  450  4800  127600  2200.000000     58  1227.034651

In [46]:
ab.groupby("Category")["Total"].agg(["min"])

             min
Category
Accessories  151
Electronics  451